course_app/urls.py
from django.contrib import admin
from django.urls import path
from .views import home,lesson

app_name='course_app'

urlpatterns=[
    path("",home, name='home'),
    path("lesson/<str:title>", lesson, name='lesson'),
]

pro_grammming/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    path('', include("course_app.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import signup,login,sign_or_log

app_name="users"

urlpatterns = [
    path('', sign_or_log, name="sign_or_log"),
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
]

course_app/models.py
from django.db import models
from django.db.models import *


# Create your models here.
class Card(models.Model):
    image=models.ImageField(upload_to='card/image/')
    title=models.CharField(max_length=255, unique=True)
    subtitle=models.CharField(max_length=500)

    def __str__(self):
        return self.title
    
class Theme(models.Model):
    title=models.CharField(max_length=150)
    card=models.ForeignKey(Card,on_delete=models.CASCADE, related_name='mavzular')

    def __str__(self):
        return self.title

class Video(models.Model):
    image=models.ImageField(upload_to='video/images')
    video=models.FileField(upload_to='video/videos')
    title=models.CharField(max_length=150)
    card=models.ForeignKey(Theme,on_delete=CASCADE, related_name='videolar')

    def __str__(self):
        return self.title

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Users(AbstractUser):
    image=models.ImageField(upload_to="users/images")
    
    def __str__(self):
        return self.username

course_app/views.py
from django.shortcuts import render
from .models import Card,Video,Theme

def home(request):
    cards=Card.objects.all()
    context={'cards':cards}
    return render(request, 'home.html', context)

def lesson(request,title):
    card=Card.objects.get(title=title)
    return render(request, 'lesson.html',{ 'card':card})

users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .form import SignUpForm, LogInForm

def sign_or_log(request):
    return render(request, "sign_or_log.html")

def signup(request):
    sign=SignUpForm()
    print("1")
    if request.method == 'POST':
        print("2")
        sign=SignUpForm(request.POST,request.FILES)
        # sign.save()
        if sign.is_valid():
            sign.save()
            print("3")
            return redirect(reverse('course_app:home'))
    return render(request, "signup.html", {'sign':sign})

def login(request):
    log=LogInForm()
    return render(request, "login.html", {'log':log})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pro Gramming</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>

        .nom {
            width: max-content;
            font-size: 20px;
            position: relative;
            cursor:auto;    
        }
        .nom::after {
            content: "";
            position: absolute;
            bottom: -10px;
            height: 4px;
            width:100%;
            left: 0;
            background-color: rgb(255, 255, 255);
            transition: 0.3s;
            transition-timing-function: ease-in-out;
            transform: scaleX(0);
        }
        .nom:hover::after{
            transform: scaleX(1);
        }

        /*  */

        h1{
            text-decoration: none;
            color: black;
        }

        .gallery{
            display: flex;
            flex-wrap: wrap;
            width: 100%;
            justify-content: center;
            align-items: center;
        }
        .content{
            width: 20%;
            margin: 15px;
            box-sizing: border-box;
            float: left;
            text-align: center;
            border-radius: 20px;
            cursor: pointer;
            padding-top: 20px;
            box-shadow: 0 14px 28px rgb(0, 238, 255),
            0 10px 10px rgb(0, 238, 255);
            transition: .4s;
            background: white;
        }
        .content:hover{
            box-sizing: 0 3px 6px rgb(0, 0, 16),
            0 3px 6px rgb(0, 0, 23);
            transform: translate(0px, -8px);
        }
        img{
            width: 200px;
            height: 200px;
            text-align: center;
            margin: 0 auto;
            display: block;
        }
        p{
            text-align: center;
            color: white;
            padding-top: 0 8px;
            color: black;
        }
        h6{
            font-size: 26px;
            text-align: center;
            color: black;
            margin: 0;
        }
        button{
            text-align: center;
            font-size: 24px;
            color: white;
            width: 100%;
            padding: 15px;
            border: 0;
            outline: none;
            cursor: pointer;
            margin-top: 5px;    
            padding-bottom: 20px;
            border-bottom-right-radius: 20px;
            border-bottom-left-radius: 20px;
        }
        .watch{
            background: rgb(195, 0, 255);
        }
        @media(max-width:1000px)
        {.content{width: 45%;}}
        
        @media(max-width:750px)
        {.content{width: 100%;}}
    
        /*  */

        /* *{
            margin: 0;
            padding: 0;
            font-family: 'Poppins','san-serif';
            box-sizing: border-box;
        }

        .accordion{
            padding-left: 10px;
            width: 300px;
        }
        .accordion li{
            list-style: none;
            width: 330px;
            margin: 10px;
            border-radius: 20px;
            margin-bottom: 20px;
            background:linear-gradient(rgb(125, 104, 243),rgb(0, 38, 255));
            box-shadow: 3px 3px 9px -1px rgb(165, 182, 14),
                        -3px -3px 9px 1px rgb(165, 182, 14);
        }
        .accordion li label{
            display: flex;
            align-items: center;
            padding: 0px;
            font-size: 18px;
            font-weight: 500;
            cursor: pointer;
        }
        label::before{
            content: '+';
            margin-right: 10px;
            font-size: 24px;
            font-weight: 600;
        }
        input[type="radio"]{
            display: none;
        }
        .accordion .ism{
            color: black;
            padding: 0 10px;
            line-height: 26px;
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.5s, padding 0.5s;
        }
        .accordion input[type="radio"]:checked + label + .ism{
            max-height: 250px;
            padding: 0px 0px 0px;
        }
        .accordion input[type="radio"]:checked + label::before{
            content: '-';
        } */
        /*  */
    </style>
</head>
<body style="background-color: rgb(33,37,41);">
    {% include "detail/navbar.html" %}
    
    {% block content %}
    {% endblock content %}

    {% include "detail/footer.html" %}
</body>
</html>
<!DOCTYPE html>
<html lang="en">

templates/detail/footer.html
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
  <div class="col-md-4 d-flex align-items-center">
    <span class="mb-3 mb-md-0 text-body-secondary"><h5 style="color: rgb(255, 255, 255);padding-left: 20px;">© 2024 Pro Gramming </h5></span>
  </div>

  <ul class="nav col-md-4 justify-content-end list-unstyled d-flex" style="padding-right: 20px;">
    <li class="ms-3"><a class="text-body-secondary" href="#"><i class="bi bi-twitter fs-2" style="color: rgb(255, 255, 255);"></i></a></li>
    <li class="ms-3"><a class="text-body-secondary" href="https://www.instagram.com/murtado_571"><i class="bi bi-instagram fs-2" style="color: rgb(255, 255, 255);"></i></a></li>
    <li class="ms-3"><a class="text-body-secondary" href="#"><i class="bi bi-facebook fs-2"  style="color: rgb(255, 255, 255);"></i></a></li>
    <li class="ms-3"><a class="text-body-secondary" href="https://t.me/mufarriyd_571"><i class="bi bi-telegram fs-2 m-1" style="color: rgb(255, 255, 255) ;"></i></i></a></li>
  </ul>
</footer>

templates/detail/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-body-primary">
  <div class="container-fluid" style="background-color: rgb(116,24,159);height: 60px;">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01"
      aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <div style="width: 250px;color: white;">
        <img style="width: 50px; height: 50px;border-radius: 25px;margin-left: 5px;display: inline;"
          src="{% static 'images/logo.png' %}" alt="">
        <h3 style="cursor: pointer;margin-left: 10px;display: inline;" class="nom">Pro Gramming</h3>
      </div>
      <!-- <h5 class="nom" style="color: white;">Pro Gramming</h5> -->
      <div style="text-align: left;width: 270px;">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <h5><a class="nav-link active" aria-current="page" href="{% url 'course_app:home' %}"
                style="width: 130px;color: white;border-radius: 10px;background-color: rgb(209,200,201);margin: 5px;text-align: center;color: rgb(116,24,159);padding-left: 20px;padding-right: 20px;"><i
                  class="bi bi-house"></i> Home</a></h5>
          </li>
          {% if request.user.is_staff %}
          <h5>
            <a class="nav-link active" aria-current="page" href="#"
              style="width: 130px;color: white;border-radius: 10px;background-color: rgb(209,200,201);margin: 5px;text-align: center;color: rgb(116,24,159);padding-left: 20px;padding-right: 20px;"><i
                class="bi bi-person-circle"></i> Admin</a>
          </h5>
          {% endif %}
        </ul>
      </div>
      <div style="position: relative;left: 660px;bottom: 5px;">
        <a href="{% url 'users:sign_or_log' %}">
          <button type="button"
            style="width: 150px;border-radius: 10px;padding: 3px;color: white;background-color: orangered;">Sign
          </button>
        </a>
      </div>
    </div>
  </div>
</nav>

templates/home.html
{% extends "base.html" %}
{% block content %}

<div class="container-fluid mt-5 mb-5">
    <div class="row">
        {% for i in cards %}
        <div class="col-3 mb-3 d-flex justify-content-center">
            <div class="gallery" style="width: 18rem;">
                <div class="content" style="width: 370px;height: 370px;">
                    <img style="width: 150px;height: 150px;border-radius: 10px;" src="{{ i.image.url }}" alt="">
                    <div style="border-radius: 10px;background-color: rgb(235, 231, 231); margin: 10px;padding: 10px;">
                        <h1 class="nommm">{{ i.title }}</h1>
                        <div class="overflow-auto" style="height: 30px;">
                            <p style="color: black;">{{ i.subtitle }}</p>
                        </div>
                    </div>
                    <a href="{% url 'course_app:lesson' i.title %}">
                        <button class="watch">Watch</button>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}  

templates/lesson.html
{% extends "base.html" %}
{% block content %}

<h1 class="text-center m-5 title" style="color: white;">{{ card }}</h1>

<div class="container-fluid">
    <div class="row">
        <div class="col-3 overflow-auto" style="height: 97vh;">
            <!---- Themes ------------------------------------>
            <div class="accordion" id="accordionExample">
                {% for m in card.mavzular.all %}
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#{{ m.title }}" aria-expanded="true" aria-controls="{{ m.title }}">
                            <h4>{{ m.title }}</h4>
                        </button>
                    </h2>
                    <div id="{{ m.title }}" class="accordion-collapse collapse" data-bs-parent="#{{ m.title }}">
                        <div class="accordion-body">
                            {% for v in m.videolar.all %}
                            <button onclick="changeVideo('{{ v.title }}', '{{ v.video.url }}', '{{ v.image.url }}')"
                                class="btn btn-outline-warning" style="font-size: 20px;">
                                {{ v.title }}
                            </button>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <!-- Video --------------------------------------->
        </div>
        <div class="col-9" style="height: 95vh;">
            <div style="height: 110vh;">
                <video style="width: 100%;border-radius: 7px;" poster="" controls loop id="video_url" src=""></video>
                <h2 id="video_title"
                    style="padding: 7px; text-align: center; margin: 10px;background-color: white;color: black;border-radius: 5px;">
                </h2>
            </div>
        </div>
    </div>
</div>

<script>
    function changeVideo(t, v, r) {
        var video = document.getElementById("video_url");
        var title = document.getElementById("video_title");

        video.src = v;
        title.innerHTML = t;
        video.poster = r;
    }
</script>

{% endblock content %}

templates/login.html
{% load static %}

<style>
    .container {
        width: 1140px;
        padding: 0;
        margin-left: 100px
    }

    .reg-item__image {
        text-align: center;
    }

    .image {
        width: 65%;
    }

    .reg-item {
        position: relative;
        bottom: 550px;
        left: 115px;
        display: inline-block;
        padding: 10px;
        height: 430px;
        margin: 100px;
        margin-top: 140px;
        border-radius: 20px;
    }

    .input {
        padding: 2px;
        display: block;
        width: 390px;
        margin: 20px;
        font-size: 27px;
        border: solid orangered 3px;
        border-radius: 10px;
        font-family: sans-serif;
        font-weight: bold;
    }

    .input:hover {
        transition-duration: 0.5s;
        display: block;
        font-size: 27px;
        border-radius: 10px;
        border: solid orange 3px;
    }

    /* ============================= */
    .submit,
    .login-button {
        cursor: pointer;
        border: 5px;
        width: 185px;
        font-family: sans-serif;
        font-size: 25px;
        font-weight: bold;
        text-align: center;
        border-radius: 5px;
        background-color: orangered;
        color: white;
        padding: 5px;
    }

    .submit:hover,
    .login-button:hover {
        transition-duration: 0.3s;
        box-shadow: 0 0 10px black;
        cursor: pointer;
        border: 5px;
        width: 185px;
        font-family: sans-serif;
        font-size: 25px;
        font-weight: bold;
        text-align: center;
        border-radius: 5px;
        background-color: orangered;
        color: white;
        padding: 5px;
    }

    .login-button:hover {
        background-color: aliceblue;
        color: orangered;
    }

    .login-link {
        text-decoration: none;
    }

    .submit {
        position: relative;
        top: 10px;
        margin-left: 15px;
    }

    .login-button {
        position: relative;
        top: 10px;
        color: orangered;
        background-color: aliceblue;
        position: relative;
        bottom: 40px;
    }

    .i {
        border-bottom-left-radius: 15px;
        width: 150px;
        height: 45px;
        position: relative;
        left: 2px;
        bottom: 10px;
        background-color: black;
        border: solid 5px black;
        color: white;
        font-family: sans-serif;
        font-size: 25px;
    }

    .a {
        border-bottom-right-radius: 15px;
        width: 150px;
        height: 45px;
        right: 2px;
        position: relative;
        bottom: 10px;
        background-color: black;
        border: solid 5px black;
        color: white;
        font-family: sans-serif;
        font-size: 25px;
    }
</style>

<div class="container">
    <div style="text-align: center;">
        <a href="{% url 'course_app:home' %}">
            <button class="i">Home</button>
        </a>
        <a href="{% url 'users:sign_or_log' %}">
            <button class="a">Sign</button>
        </a>
    </div>
    <div class="reg-item__image">
        <img class="image" src="{% static 'images/fon2.png' %}" alt="">
    </div>
    <form action="" method="post" style="height: 60%">
        <div class="reg">
            <div class="reg-item">
                {% csrf_token %}
                {{ log.username }}
                {{ log.password }}
                <div class="reg-item__log" style="margin-left: 20px;position: relative;bottom: 10px;">
                    <a href="{% url 'users:signup' %}" type="button" class="login-link">
                        <button class="login-button">Log In</button>
                    </a>
                    <button type="submit" class="submit">Sign Up</button>
                </div>
            </div>
        </div>
    </form>
</div>

templates/sign_or_log.html
{% load static %}

<style>
    .container {
        width: 1140px;
        padding: 0;
        margin-left: 100px
    }

    .reg-item__image {
        text-align: center;
    }

    .image {
        width: 65%;
    }

    .submit,
    .login-button {
        margin: 5px;
        cursor: pointer;
        border: 5px;
        width: 300px;
        float: left;
        font-family: sans-serif;
        font-size: 35px;
        font-weight: bold;
        text-align: center;
        border-radius: 5px;
        background-color: orangered;
        color: white;
        padding: 5px;
    }

    .submit:hover,
    .login-button:hover {
        transition-duration: 0.3s;
        box-shadow: 0 0 10px black;
        cursor: pointer;
        border: 5px;
        width: 300px;
        font-family: sans-serif;
        font-size: 35px;
        font-weight: bold;
        text-align: center;
        border-radius: 5px;
        background-color: orangered;
        color: white;
        padding: 5px;
    }

    .login-button {
        background-color: aliceblue;
        color: orangered;
    }

    .login-button:hover {
        background-color: white;
        color: orangered;
    }

    .item {
        position: relative;
        bottom: 350px;
        right: 415px;
        width: 200px;
        height: 100px;
        background-color: rgba(185, 180, 180, 0);
    }

    .i {
        border-bottom-right-radius: 15px;
        border-bottom-left-radius: 15px;
        width: 300px;
        height: 45px;
        position: relative;
        bottom: 10px;
        background-color: black;
        border: solid 5px black;
        color: white;
        font-family: sans-serif;
        font-size: 25px;
    }
</style>
<div class="container">
    <div style="text-align: center;">
        <a href="{% url 'course_app:home' %}">
            <button class="i">Home</button>
        </a>
    </div>
    <div class="reg-item__image">
        <img class="image" src="{% static 'images/fon2.png' %}" alt="">
    </div>
    <div style="margin-left: 700px;float: left;">
        <div class="item">
            <a href="signup/">
                <button class="submit">Sign Up</button>
            </a>
            <a href="login/">
                <button class="login-button">Log In</button>
            </a>
        </div>
    </div>
</div>

templates/signup.html
{% load static %}

<style>
    .container {
        width: 1140px;
        padding: 0;
        margin-left: 100px
    }

    .reg-item__image {
        text-align: center;
    }

    .image {
        width: 65%;
    }

    .reg-item {
        position: relative;
        bottom: 600px;
        left: 115px;
        /* box-shadow: 0 0 10px black; */
        display: inline-block;
        padding: 10px;
        /* background-color: rgba(182, 175, 175, 0.822); */
        height: 430px;
        margin: 100px;
        margin-top: 140px;
        border-radius: 20px;
    }

    .open_image {
        margin-left: 20px;
        border-radius: 5px;
        border: solid 2px orangered;
    }

    .input {
        padding: 1px;
        display: block;
        width: 390px;
        margin: 20px;
        font-size: 19px;
        border: solid orangered 2px;
        border-radius: 10px;
        font-family: sans-serif;
        font-weight: bold;
    }

    .input:hover {
        transition-duration: 0.5s;
        display: block;
        font-size: 19px;
        border-radius: 10px;
        border: solid orange 2px;
    }

    /* ============================= */
    .submit,
    .login-button {
        cursor: pointer;
        border: 5px;
        width: 185px;
        font-family: sans-serif;
        font-size: 20px;
        font-weight: bold;
        text-align: center;
        border-radius: 5px;
        background-color: orangered;
        color: white;
        padding: 3px;
    }

    .submit:hover,
    .login-button:hover {
        transition-duration: 0.3s;
        box-shadow: 0 0 10px black;
        cursor: pointer;
        border: 5px;
        width: 185px;
        font-family: sans-serif;
        font-size: 20px;
        font-weight: bold;
        text-align: center;
        border-radius: 5px;
        background-color: orangered;
        color: white;
        padding: 3px;
    }

    .login-button:hover {
        background-color: aliceblue;
        color: orangered;
    }

    .login-link {
        text-decoration: none;
    }

    .submit {
        position: relative;
        bottom: -10px;

    }

    .login-button {
        position: relative;
        top: 10px;
        color: orangered;
        background-color: aliceblue;
        position: relative;
        bottom: 40px;
        left: 15px;
    }

    .i {
        border-bottom-left-radius: 15px;
        width: 150px;
        height: 45px;
        position: relative;
        left: 2px;
        bottom: 10px;
        background-color: black;
        border: solid 5px black;
        color: white;
        font-family: sans-serif;
        font-size: 25px;
    }

    .a {
        border-bottom-right-radius: 15px;
        width: 150px;
        height: 45px;
        right: 2px;
        position: relative;
        bottom: 10px;
        background-color: black;
        border: solid 5px black;
        color: white;
        font-family: sans-serif;
        font-size: 25px;
    }

    .asosiy {
        margin-left: 30px;

    }

    .reg-item__log {
        position: relative;
        left: 20px;
    }
</style>
<div class="container">
    <div style="text-align: center;">
        <a href="{% url 'course_app:home' %}">
            <button class="i">Home</button>
        </a>
        <a href="{% url 'users:sign_or_log' %}">
            <button class="a">Sign</button>
        </a>
    </div>
    <div class="reg-item__image">
        <img class="image" src="{% static 'images/fon2.png' %}" alt="">
    </div>
    <form action="" method="post" enctype="multipart/form-data" style="height: 60%">
        <div class="reg">

            <div class="reg-item">
                {% csrf_token %}
                {{ sign.image }}
                {{ sign.first_name }}
                {{ sign.last_name }}
                {{ sign.email }}
                {{ sign.username }}
                <div class="asosiy" style="position: relative;bottom: 10px;">
                    {{ sign.password1 }}
                    {{ sign.password2 }}
                    {{ sign.errors }}
                </div>
                <div class="reg-item__log">
                    <button type="submit" class="submit">Sign Up</button>
                    <a href="{% url 'users:login' %}" type="button" class="login-link">
                        <button class="login-button">Log In</button>
                    </a>
                </div>
            </div>
        </div>
    </form>
</div>